version: '3'
services:
  app:
    network_mode: "bridge"
    image: nginx # DockerHub image
    ports:
      - 80:80
  app-with-secret:
    image: alpine-with-secret
    networks:
      - network1
  app-with-secret-nonenetwork:
    image: alpine-with-secret
    # none disable all container networking, network_mode set service containers network mode
    network_mode: "none"
  # two more alpine container
  client1:
    image: alpine
    network_mode: "bridge"
    links:
      - app
    command: tail -f /dev/null
  client2:
    image: alpine
    network_mode: "bridge"
    links:
      - app
    command: tail -f /dev/null
  # add another two alpine containers that use vip-clients network
  vip-client1:
    image: alpine
    networks:
      - vip-clients
    container_name: vip-client1
    command: tail -f /dev/null
  vip-client2:
    image: alpine
    networks:
      - vip-clients
    container_name: vip-client2
    command: tail -f /dev/null

networks:
  network1:
    name: padlock
    external: false
    internal: true
  vip-clients:
    driver: bridge
